[package]
name = "configuration"
version = "0.1.0"
edition = "2018"

[dependencies]
normalization = { path = "../normalization" }
rpc = { path = "../rpc" }
discovery = { path = "../discovery" }
tokio = { version = "1", features = ["full"] }
